
import Navbar from '@/app/component/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { orbitron } from './fonts'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'India Gamer',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en" className={orbitron.variable}>
      <body className="flex flex-col  py-2 px-4  min-h-screen bg-orange-50">
       
        <header>
  <Navbar />
        </header>
        <main className="grow py-3">
        {children}
        </main>
       
        <footer className="border-t py-3 text-center text-xs  ">
          Game data and images courtesy of <a href='https://rawg.io/' target='_blank'>RAWG</a>
        </footer>
        </body>
    </html>
  )
}
